version: '3.4'

networks:
    VitaQuestNetwork:

services:
  vitaquest:
    image: ${DOCKER_REGISTRY-}vitaquest
    build:
      context: .
      dockerfile: VitaQuest/Dockerfile
    depends_on:
        - SQLServer-db
    ports:
      - "443:443"
      - "8001:80"
    networks:
      - VitaQuestNetwork
  SQLServer-db:
    container_name: SQLServer-db
    image: mcr.microsoft.com/mssql/server
    user: root
    ports:
      - "1433:1433"
    expose:
      - "1433" 
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Str0ngPa$$w0rd"
    volumes:
      - sqlServerDB:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
    networks:
      - VitaQuestNetwork
volumes:
    sqlServerDB:    